name: "Send Email"
description: "GitHub Action to send email using nodemailer"
inputs:
  to:
    description: "Recipient email address"
    required: true
  subject:
    description: "Email subject"
    required: true
  text:
    description: "Plain text message"
    required: true
  html:
    description: "HTML message (optional)"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
